### ISSUE TITLE
RuntimeWarning: Model '...' was already registered.

### ISSUE THREAD

**Issue by macieyn** [rvinzent/django-dynamic-models#18]
Hi. I've written this code to add verbose_name to a field when model is created:
```python
def create_model(model_name, *args):
    model_schema = models.ModelSchema.objects.create(name=model_name)
    for arg in args:
        field_schema = models.FieldSchema.objects.create(name=arg[0], data_type=arg[1])
        model_schema.add_field(field_schema, unique=False, null=False)
    model = model_schema.as_model()
    for arg in args:
        field = model._meta.get_field(arg[0])
        field.verbose_name = arg[2]

create_model('car', ('max_speed', 'integer', 'MAX SPEED'), ('color', 'character', 'COLOR'))
create_model('cable', ('length', 'integer', 'LENGTH'), ('color', 'character', 'COLOR'))
```
Which does what I wanted. After first run on clean database no warnings, no errors, but after second run I get this warning every time:
```
/home/maciej/Pulpit/ekosys2/venv/lib/python3.7/site-packages/django/db/models/base.py:320: RuntimeWarning: Model 'components.cables' was already registered. Reloading models is not advised as it can lead to inconsistencies, most notably with related models.
  new_class._meta.apps.register_model(new_class._meta.app_label, new_class)
```
Models are implemented as in readme. They are created properly.
Any thoughts on what is going on?

**Comment by rvinzent** [comment]
@macieyn 
Under the hood Django is keeping track of models in your app in a thing called the model registry. When you subclass `models.Model` it adds the model to the model registry. `dynamic_models` creates the model classes at runtime, so the model is "registered" to Django each type your model class is created, e.g. when `as_model()` is called. Django attempts to register the model and if the model is the same as one that is already registered, it throws this warning. 

The reason your code is raising the warning is because there are two `ModelSchema` instances with the same name (or there is a bug somewhere in the registry logic). The name field should be unique across your application. There should be a unique constraint on the `ModelSchema.name` to help prevent this. 

Hope this helps!

PS. I am working on the 0.2 release which will present a simpler API and fix a couple of bugs that have come up in the 0.1 version :)
